### ISSUE TITLE
[BUG]:  react-native-size-matters crashes on ios

### ISSUE THREAD

**Issue by Nadimkhan120** [ildfreelancer/react-native-better-boilerplate#1]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

Invariant Violation: [133,"RCTView",81,{"flex":1,"paddingHorizontal":"<<NaN>>"}] is not usable as a native method argument
i just run the project on ios simulator, and app crashes, its becuase of @lib/react-native-size-matters

### Version

1.3.2

### On which OS this issue appear on?

- [X] IOS
- [ ] Android

### Desktop OS

mac

**Comment by ildfreelancer** [comment]
@Nadimkhan120 Hey, thanks for reporting the issue.

I think you didn't read README

This project is setup environment automatically using react-native-config.

In order to resolve your issue.
At the root, you only need to run the command line

```
cp .env.example to .env.development
```

In .env.development, depends on design frame resolution, you can set it as default, then with power of react-native-size-matter, the app will resize automatically for all devices.
